### ISSUE TITLE
GRM output doesn't work

### ISSUE THREAD

**Issue by robertson-mark** [USDA-ARS-NWRC/basin_setup#25]
grm -b lakes -t topo.nc -i USCALB20190611_SUPERsnow_depth_clipped.tif -o test.nc --debug

results in the following errors:

Grid Resizing and Matching Script v0.8.2
===========================================

INFO  Calculating dates and sorting images for processing...
INFO  Number of images being processed: 1
INFO  
INFO  Processing USCALB20190611_SUPERsnow_depth_clipped.tif
WARNING Skipping USCALB20190611_SUPERsnow_depth_clipped.tif due to error
WARNING No images were processed!
Traceback (most recent call last):
  File "/usr/local/bin/grm", line 534, in <module>
    main()
  File "/usr/local/bin/grm", line 525, in main
    g.log.info("Grid Resizing and Matching Complete. {1}/{2} files processed."
UnboundLocalError: local variable 'g' referenced before assignment
root@1c70e80b270e:/data# grm -b lakes -t topo.nc -i USCALB20190611_SUPERsnow_depth_clipped.tif -o test.nc --debug
INFO  

Grid Resizing and Matching Script v0.8.2
===========================================

INFO  Calculating dates and sorting images for processing...
INFO  Number of images being processed: 1
INFO  
INFO  Processing USCALB20190611_SUPERsnow_depth_clipped.tif
Traceback (most recent call last):
  File "/usr/local/bin/grm", line 534, in <module>
    main()
  File "/usr/local/bin/grm", line 514, in main
    output=output,
UnboundLocalError: local variable 'output' referenced before assignment

**Comment by micahjohnson150** [comment]
This is an error but per the documentation, --output is the path to the output folder.  I will get the error fixed today.
