### ISSUE TITLE
GRM doesn't consider if the topo matches an existing lidar netcdf

### ISSUE THREAD

**Issue by robertson-mark** [USDA-ARS-NWRC/basin_setup#30]
GRM failing to add a single image to existing lidar_depths.nc file. Run in Lakes:

/data/snowpack/lidar/Lakes/2019

root@a4fe363f530c:/data# grm -b lakes -t lakes_topo.nc -i aso/USCALB20190715_SUPERsnow_depth_50p0m_agg.tif -r near -d
INFO  

Grid Resizing and Matching Script v0.9.0
===========================================

INFO  Calculating dates and sorting images for processing...
INFO  Number of images being processed: 1
INFO  
INFO  Processing USCALB20190715_SUPERsnow_depth_50p0m_agg.tif
INFO  Getting Topo attributes...
INFO  Using topo cell size which is 50 meters
INFO  Working on the Mammoth Lakes Basin
INFO  Rescaling image raster from 50 to 50
DEBUG Writing grid adjusted image to:
./output/tmp/USCALB20190715_SUPERsnow_depth_50p0m_agg.nc
DEBUG Executing: gdalwarp -r near -of NETCDF -overwrite -srcnodata -9999 -dstnodata -9999 -te 256650 4096650 353300 4179550 -ts 1934 1659 aso/USCALB20190715_SUPERsnow_depth_50p0m_agg.tif ./output/tmp/USCALB20190715_SUPERsnow_depth_50p0m_agg.nc
Traceback (most recent call last):
  File "/usr/local/bin/grm", line 546, in <module>
    main()
  File "/usr/local/bin/grm", line 530, in main
    g.add_to_collection()
  File "/usr/local/bin/grm", line 234, in add_to_collection
    "".format(self.water_year))
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'

**Comment by micahjohnson150** [comment]
The issue here is that the Lidar.nc file was previously existing and was generated using a different topo with different dimensions. The immediate fix is using the correct topo ;).
The feature needed here is one that considers whether the lidar.nc exists, if the lidar.nc already exists look for a mismatch between the topo and the current lidar.nc file.
