### ISSUE TITLE
Vegetation tau and k are preallocated with zeros which have meaning

### ISSUE THREAD

**Issue by scotthavens** [USDA-ARS-NWRC/basin_setup#31]
The vegetation parameterizations are being preallocated [with zeros](https://github.com/USDA-ARS-NWRC/basin_setup/blob/667b0195c6ab65d4b3c9b914f04c2a28d1086bca/basin_setup.py#L971) which have meaning. So if there is a case where a vegetation isn't properly classified, then tau and k still have meaning.

The solution proposed would be to preallocate with `nan` and error if any `nan` values are found. A csv file of classifications will be kept with `basin_setup` that will be imported. When using docker, this will allow a user to override the classification with their own.

[LF_veg_params.txt](https://github.com/USDA-ARS-NWRC/basin_setup/files/3433025/LF_veg_params.txt)

**Comment by micahjohnson150** [comment]
Making progress here, Its developed and I am going through testing. 

RCEW, BRB, senator beck, and the Gunnison have undefined veg values. Not sure if that's something we want to address now. 

Here's whats missing currently.

BRB -  3045, 3046, 3047, 3050, 3053, 3055, 3056, 3065, 3086, 3106, 3115, 3123, 3134, 3139, 3140, 3142, 3159, 3160, 3161, 3166, 3167, 3169, 3203, 3227, 3233, 3234, 3235, 3236, 3237, 3251


RCEW - 3045, 3047, 3053, 3055, 3065, 3106, 3123, 3139, 3140, 3142, 3159, 3160, 3161, 3165, 3166, 3169, 3227, 3232, 3234, 3251


senator beck - 3055, 3056, 3086, 3144, 3146


 Gunnison - 3016, 3049, 3050, 3051, 3052, 3054, 3055, 3056, 3059, 3064, 3070, 3086, 3093, 3107, 3115, 3117, 3119, 3143, 3144, 3146, 3159, 3160, 3180, 3214, 3217, 3251, 3259, 3940
