### ISSUE TITLE
Take data reduction a bit further

### ISSUE THREAD

**Issue by micahjohnson150** [USDA-ARS-NWRC/basin_setup#33]
Decided to look at this again was first addressed by #8 and work was accomplished there.

Here I am recommending:
* veg_type from U4 (unsigned int 32bit) - U2 (unsigned int 16 bit),
* All other variables except for masks to f4 (floating 32)
*  Add in some more reporting on dataetypes while processing the topo
* Add in zlib compression and a significant digits=3, this will only work for netcdf4 which I am not sure we have ever made netcdfs in 3.

**Comment by micahjohnson150** [comment]
Quick tests here with the new code:
Here is the dem difference in the kaweah. Pretty minor. Certainly in the noise.

![kaweah_dem_topo_diff](https://user-images.githubusercontent.com/7646021/62960133-440edb80-bdb7-11e9-89c0-2e3c1f6b16c9.png)


Some quick stats on the file size changes compared to WY19 ops topos to now (including new veg data):
Tuol : -33Mb
Merced: -43Mb
SJ: -66Mb
Lakes: -0.4Mb
Kings: -18.74Mb
Kaweah: -18Mb

**Comment by micahjohnson150** [comment]
I was a little concerned about how this would affect the veg)k and veg_tau (which has just changed and is being evaluated right now (https://github.com/USDA-ARS-NWRC/basin_ops/issues/4),  since they are usually just a fraction of 1. The difference is still extremely small.

![kaweah_veg_k_topo_diff](https://user-images.githubusercontent.com/7646021/62960844-c5b33900-bdb8-11e9-87a1-5747fda28416.png)

**Comment by micahjohnson150** [comment]
@scotthavens let me know if you think this is acceptable data loss and I will push this through.

**Comment by scotthavens** [comment]
On what variables are the significant digits applied? 3 seems fine for elevation, but veg k can be out to 3 digits so should we limit ourselves to just save a few MB?

What about the dimension data types? The `x` and `y` data type can have a good impact as well.

What were the size of the original topo files?

**Comment by micahjohnson150** [comment]
@micahjohnson150 Make sure we specify in the docs that the CSV has to have no greater than whatever precision we use.

**Comment by micahjohnson150** [comment]
Ok per our convo I added in Veg_k and Veg_tau as having a preicsion of 4. Everything else will be 3.

To answer your question and for documentation sake here are the types where DEV= now and OPS = WY2019:

		Variable y: Dev type = float32, Ops type = float32
		Variable x: Dev type = float32, Ops type = float32
		Variable veg_height: Dev type = float32, Ops type = float32
		Variable dem: Dev type = float32, Ops type = float32
		Variable veg_type: Dev type = uint16, Ops type = uint32
		Variable veg_k: Dev type = float32, Ops type = float32
		Variable veg_tau: Dev type = float32, Ops type = float32
		Variable mask: Dev type = uint8, Ops type = uint8

File Size changes with relative change associated.

Merced: -43.0965Mb (-80.96%)
Kaweah: -18.3531Mb (-75.58%)
Kings: -66.2465Mb (-87.61%)
Tuolumne: -32.8998Mb (-78.45%)
San Joaquin: -64.5801Mb (-80.48%)
Lakes: -0.3490Mb (-61.69%)
