### ISSUE TITLE
input, output, and desired boundaries still do not match

### ISSUE THREAD

**Issue by etrujil** [USDA-ARS-NWRC/basin_setup#36]
We need to figure this out, the netcdf topo.nc file still has a miss-match with the desired extent.
The min, max of the x, y fields of topo.nc are:
[238647.0 307297.0], [4179267.0, 4246167.0 ]
Which means an extent of [xll, yll, xur, yur, dx, dy] (from parse_extent, and same that you see in QGIS): 
[238622.0, 4179242.0, 307322.0, 4246192.0, 50.0, 50.0]
These are off by half a cellsize of 50m.
The extend given to the basin_setup command is --extent 238647 4179267 307347 4246217.
I think the issue is how the x and y fields are given to create the netCDF file.

**Comment by micahjohnson150** [comment]
Same as #34
