### ISSUE TITLE
Missing Veg Values for the Boise River Basin

### ISSUE THREAD

**Issue by micahjohnson150** [USDA-ARS-NWRC/basin_setup#45]
@scotthavens , @etrujil , @Hedrick-ARS  We are missing the following veg values for the BRB. For now I have it generating the topo with nans at those values so no rush on my end.

* 3046
* 3047
* 3053
* 3065
* 3134
* 3142
* 3161
* 3166
* 3167
* 3169
* 3233
* 3234
* 3235
* 3236
* 3237

**Comment by micahjohnson150** [comment]
Here are the values being used for BRB in basin setup.

| VEG | Class Name | Tau | K |
|-----|:------------|:-----|:---|                                                                                                        
| 3046 | Northern Rocky Mountain Subalpine Woodland and... | 0.20 | 0.040 |
| 3047 | Northern Rocky Mountain Mesic Montane Mixed Co... | 0.16 | 0.074 |
| 3053 | Northern Rocky Mountain Ponderosa Pine Woodlan... | 0.20 | 0.040 |
| 3065 |               Columbia Plateau Scabland Shrubland | 1.00 | 0.000 |
| 3134 |  Columbia Basin Foothill and Canyon Dry Grassland | 1.00 | 0.000 |
| 3142 |                    Columbia Basin Palouse Prairie | 1.00 | 0.000 |
| 3161 |             Northern Rocky Mountain Conifer Swamp | 0.30 | 0.033 |
| 3166 | Middle Rocky Mountain Montane Douglas-fir Fore... | 0.16 | 0.074 |
| 3167 |    Rocky Mountain Poor-Site Lodgepole Pine Forest | 0.16 | 0.074 |
| 3169 | Northern Rocky Mountain Subalpine Deciduous Sh... | 1.00 | 0.000 |
| 3233 |                      Subalpine Douglas-fir Forest | 0.20 | 0.040 |
| 3234 |                  Mesic Montane Douglas-fir Forest | 0.20 | 0.040 |
| 3235 |                  Xeric Montane Douglas-fir Forest | 0.20 | 0.040 |
| 3236 |                    Subalpine Western Larch Forest | 0.44 | 0.025 |
| 3237 |                Mesic Montane Western Larch Forest | 0.44 | 0.025 |

**Comment by scotthavens** [comment]
Looks good.
