### ISSUE TITLE
Help for -ex option in basin_setup command

### ISSUE THREAD

**Issue by etrujil** [USDA-ARS-NWRC/basin_setup#56]
Help for 
 p.add_argument('-ex', '--extents', dest='desired_extents', nargs=4, required=False,
                   help="Number of cells to add on to the domain for each"
                   " side. Format is [Left, Bottom, Right, Top]")
in basin_setup.py

needs to be replaced with something like:
"Coordinated in output coordinate system of the desired boundaries for the modeling domain"

**Comment by scotthavens** [comment]
Fixed with #59 with the configuration option to specify the coordinate extents.
